#!/usr/bin/env python3
"""Build sql/02_seed.sql from data/catalog.json.

Run from the project root:  python3 -I tools/build_seed.py

IDs are deterministic (UUID v5 from slugs), so re-running the seed
updates rows in place instead of duplicating them. Re-running resets
each program's catalog fields (status, contacts, rules) to the
catalog's values; the agent_notes column is kept.

Generated SQL is checked with sqlparse before it is written: one
statement per row group, no comment placed after a comma (the
HomeAccessIQ handoff #9 lesson), and the file ends inside a single
transaction.
"""
import json
import pathlib
import sys
import uuid

import sqlparse

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATALOG = ROOT / "data" / "catalog.json"
OUT = ROOT / "sql" / "02_seed.sql"
NS = uuid.UUID("6f1c2f1e-0e6a-4c8e-9a51-5e1d0000e651")

PROGRAM_COLUMNS = [
    "slug", "name", "administering_entity", "reach", "program_type", "description",
    "benefit_summary", "max_amount", "strings_attached", "how_to_apply", "call_script",
    "source_url", "funding_status", "status_note", "reopens_note", "is_emergency_route",
    "open_questions", "last_verified_date",
]


def uid(*parts):
    return str(uuid.uuid5(NS, "/".join(str(p) for p in parts)))


def lit(value):
    """Render a Python value as a SQL literal."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, list):
        if not value:
            return "'{}'::text[]"
        return "array[" + ", ".join(lit(v) for v in value) + "]::text[]"
    if isinstance(value, dict):
        return "'" + json.dumps(value, ensure_ascii=False).replace("'", "''") + "'::jsonb"
    return "'" + str(value).replace("'", "''") + "'"


def values_block(rows):
    return ",\n".join("  (" + ", ".join(row) + ")" for row in rows)


def main():
    catalog = json.loads(CATALOG.read_text())
    verified_on = catalog["verified_on"]
    poverty = catalog["poverty_guidelines_2026"]
    programs = catalog["programs"]

    slugs = [p["slug"] for p in programs]
    if len(slugs) != len(set(slugs)):
        sys.exit("Duplicate program slug in catalog")

    out = []
    out.append("-- ============================================================")
    out.append("-- EHS-IQ seed data. GENERATED by tools/build_seed.py from")
    out.append("-- data/catalog.json. Do not edit by hand; edit the catalog and")
    out.append("-- rebuild. Run after 01_schema.sql, in the EHS-IQ project only.")
    out.append(f"-- Catalog verified on {verified_on}. Safe to re-run.")
    out.append("-- ============================================================")
    out.append("")
    out.append("begin;")
    out.append("")

    # ---------- Lookup tables and values ----------
    table_rows = []
    value_rows = []
    for t in catalog["lookup_tables"]:
        tid = uid("lookup", t["table_name"])
        table_rows.append([lit(tid), lit(t["table_name"]), lit(t["description"]), lit(t["value_type"])])
        if "poverty_multiple" in t:
            series = [{"county_fips": None,
                       "by_household_size": [round(p * t["poverty_multiple"]) for p in poverty]}]
        else:
            series = t.get("values", [])
        for s in series:
            for size, amount in enumerate(s["by_household_size"], start=1):
                vid = uid("lookupvalue", t["table_name"], s["county_fips"] or "all", size)
                value_rows.append([lit(vid), lit(tid), lit("IN"), lit(s["county_fips"]), lit(size),
                                   lit(amount), lit(t["effective_date"]), lit(t["source_url"]), lit(verified_on)])

    out.append("-- Income reference tables")
    out.append("insert into geo_lookup_tables (id, table_name, description, value_type)")
    out.append("values")
    out.append(values_block(table_rows))
    out.append("on conflict (table_name) do update set")
    out.append("  description = excluded.description,")
    out.append("  value_type = excluded.value_type;")
    out.append("")
    table_names = [lit(t["table_name"]) for t in catalog["lookup_tables"]]
    out.append("delete from geo_lookup_values where lookup_table_id in (")
    out.append("  select id from geo_lookup_tables where table_name in (" + ", ".join(table_names) + ")")
    out.append(");")
    out.append("")
    if value_rows:
        out.append("insert into geo_lookup_values (id, lookup_table_id, state_code, county_fips, household_size, "
                   "numeric_value, effective_date, source_url, last_verified_date)")
        out.append("values")
        out.append(values_block(value_rows))
        out.append(";")
        out.append("")

    # ---------- Programs ----------
    program_rows = []
    for p in programs:
        row = [lit(uid("program", p["slug"]))]
        for col in PROGRAM_COLUMNS:
            value = verified_on if col == "last_verified_date" else p.get(col)
            row.append(lit(value))
        program_rows.append(row)

    out.append("-- Programs")
    out.append("insert into programs (id, " + ", ".join(PROGRAM_COLUMNS) + ")")
    out.append("values")
    out.append(values_block(program_rows))
    out.append("on conflict (slug) do update set")
    updates = [f"  {c} = excluded.{c}" for c in PROGRAM_COLUMNS if c != "slug"]
    out.append(",\n".join(updates) + ";")
    out.append("")

    program_ids = ", ".join(lit(uid("program", s)) for s in slugs)
    for child in ("program_contacts", "program_eligibility_rules", "program_requirements"):
        out.append(f"delete from {child} where program_id in ({program_ids});")
    out.append("")

    contact_rows, rule_rows, req_rows = [], [], []
    for p in programs:
        pid = uid("program", p["slug"])
        for i, c in enumerate(p.get("contacts", [])):
            contact_rows.append([lit(uid("contact", p["slug"], i)), lit(pid), lit(c["label"]),
                                 lit(c.get("phone")), lit(c.get("email")), lit(c.get("website")),
                                 lit(c.get("address")), lit(c.get("county_fips")), lit(c.get("notes")), lit(i)])
        for i, r in enumerate(p.get("rules", [])):
            rule_rows.append([lit(uid("rule", p["slug"], i)), lit(pid), lit(r["rule_type"]) + "::rule_type",
                              lit(r["rule_config"]), lit(r.get("description")), lit(i)])
        for i, q in enumerate(p.get("requirements", [])):
            req_rows.append([lit(uid("req", p["slug"], i)), lit(pid), lit(q["requirement_type"]),
                             lit(q["description"]), lit(i)])

    out.append("-- Contacts")
    out.append("insert into program_contacts (id, program_id, label, phone, email, website, address, county_fips, notes, sort_order)")
    out.append("values")
    out.append(values_block(contact_rows))
    out.append(";")
    out.append("")
    out.append("-- Eligibility rules")
    out.append("insert into program_eligibility_rules (id, program_id, rule_type, rule_config, description, evaluation_order)")
    out.append("values")
    out.append(values_block(rule_rows))
    out.append(";")
    out.append("")
    if req_rows:
        out.append("-- Requirements printed on the plan")
        out.append("insert into program_requirements (id, program_id, requirement_type, description, sort_order)")
        out.append("values")
        out.append(values_block(req_rows))
        out.append(";")
        out.append("")

    out.append("commit;")
    sql = "\n".join(out) + "\n"

    # ---------- Validation ----------
    statements = [s for s in sqlparse.split(sql) if s.strip()]
    for s in statements:
        body = sqlparse.format(s, strip_comments=True).strip()
        if not body.endswith(";"):
            sys.exit(f"Statement does not end with a semicolon:\n{body[:200]}")
    for number, line in enumerate(sql.splitlines(), start=1):
        if line.lstrip().startswith("--"):
            continue
        in_string = False
        for i, ch in enumerate(line):
            if ch == "'":
                in_string = not in_string
            elif not in_string and line.startswith("--", i):
                sys.exit(f"Line {number}: inline comment on a code line could swallow a separator: {line[:120]}")

    OUT.write_text(sql)
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(statements)} statements, "
          f"{len(programs)} programs, {len(rule_rows)} rules, {len(contact_rows)} contacts, "
          f"{len(req_rows)} requirements, {len(value_rows)} income values")


if __name__ == "__main__":
    main()
